import type { BuildingDef } from '../sim/types.js';

const h = (hours: number, minutes = 0) => hours * 60 + minutes;

// M1 building set: enough to stage the bakery story from spec section 3 and give residents
// homes, work, gathering places and somewhere green to wander. Economy values arrive in M2.
export const BUILDINGS: Record<string, BuildingDef> = {
  tent: {
    type: 'tent',
    cost: 0,
    blurb: 'A canvas roof for one.',
    name: 'Tent',
    kind: 'home',
    size: [1, 1],
    emits: {},
    radius: 0,
    activities: ['sleep', 'eat', 'rest'],
    capacity: 1,
  },
  cottage: {
    type: 'cottage',
    cost: 10,
    blurb: 'A home for two.',
    name: 'Cottage',
    kind: 'home',
    size: [2, 2],
    emits: {},
    radius: 0,
    activities: ['sleep', 'eat', 'rest'],
    capacity: 2,
  },
  well: {
    type: 'well',
    cost: 4,
    blurb: 'Water, and a reason to stop and chat.',
    name: 'Well',
    kind: 'civic',
    size: [1, 1],
    emits: { bustle: 0.2, water: 0.3 },
    radius: 1,
    activities: [],
  },
  commons: {
    type: 'commons',
    cost: 6,
    blurb: 'An open green for gathering and festivals.',
    comfortable: 5,
    name: 'Commons',
    kind: 'social',
    size: [3, 3],
    emits: { green: 0.4, bustle: 0.3 },
    radius: 2,
    activities: ['socialize', 'stroll'],
  },
  teahouse: {
    type: 'teahouse',
    cost: 12,
    blurb: 'Tea, warmth and evening company.',
    comfortable: 3,
    name: 'Teahouse',
    kind: 'social',
    size: [2, 2],
    emits: { bustle: 0.5, scent: 0.3 },
    radius: 2,
    activities: ['socialize', 'eat'],
    open: [h(7), h(21, 30)],
  },
  oak: {
    type: 'oak',
    cost: 0,
    blurb: 'An old tree to sit beneath.',
    comfortable: 3,
    name: 'Old oak',
    kind: 'nature',
    size: [1, 1],
    emits: { green: 0.6 },
    radius: 2,
    activities: ['socialize', 'stroll'],
  },
  brook: {
    type: 'brook',
    cost: 0,
    blurb: 'Running water.',
    name: 'Brook',
    kind: 'nature',
    size: [1, 10],
    emits: { water: 0.8, green: 0.3 },
    radius: 2,
    activities: ['stroll'],
  },
  garden: {
    type: 'garden',
    cost: 3,
    blurb: 'Plots that feed the town.',
    produces: { food: 0.9 },
    name: 'Garden plots',
    kind: 'work',
    size: [2, 2],
    emits: { green: 0.5 },
    radius: 1,
    activities: ['work', 'stroll'],
    capacity: 3,
    shift: [h(9), h(13)],
  },
  bakery: {
    type: 'bakery',
    cost: 10,
    blurb: 'Bread for everyone. The ovens start at four.',
    produces: { food: 1.2 },
    name: 'Bakery',
    kind: 'work',
    size: [2, 2],
    emits: { scent: 0.7, bustle: 0.2 },
    emitsWhenWorked: { noise: 0.8 },
    radius: 4,
    activities: ['work', 'eat'],
    capacity: 1,
    shift: [h(4), h(11)],
  },
  workshop: {
    type: 'workshop',
    cost: 8,
    blurb: 'A place to make and mend. Noisy by day.',
    name: 'Workshop',
    kind: 'work',
    size: [2, 1],
    emits: {},
    emitsWhenWorked: { noise: 0.5 },
    radius: 2,
    activities: ['work'],
    capacity: 2,
    shift: [h(9), h(17)],
  },
  woodlot: {
    type: 'woodlot',
    cost: 2,
    blurb: 'Trees tended for timber.',
    produces: { timber: 0.3 },
    name: 'Woodlot',
    kind: 'work',
    size: [2, 2],
    emits: { green: 0.6 },
    emitsWhenWorked: { noise: 0.4 },
    radius: 2,
    activities: ['work', 'stroll'],
    capacity: 2,
    shift: [h(8), h(15)],
  },
  jetty: {
    type: 'jetty',
    cost: 3,
    blurb: 'Fishing from the brook.',
    produces: { food: 0.6 },
    name: 'Fishing jetty',
    kind: 'work',
    size: [1, 1],
    emits: { water: 0.4 },
    radius: 1,
    activities: ['work', 'stroll'],
    capacity: 1,
    shift: [h(6), h(12)],
  },
  bench: {
    type: 'bench',
    cost: 2,
    blurb: 'Somewhere to sit and watch the world.',
    comfortable: 2,
    name: 'Bench',
    kind: 'decor',
    size: [1, 1],
    emits: {},
    radius: 0,
    activities: ['socialize', 'stroll'],
  },
  hedge: {
    type: 'hedge',
    cost: 1,
    blurb: 'Softens noise and adds green.',
    name: 'Hedge',
    kind: 'decor',
    size: [1, 1],
    emits: { noise: -0.6, green: 0.3 },
    radius: 2,
    activities: [],
  },
  flowerbed: {
    type: 'flowerbed',
    cost: 0,
    blurb: 'Colour and scent.',
    name: 'Flower bed',
    kind: 'decor',
    size: [1, 1],
    emits: { green: 0.3, scent: 0.3 },
    radius: 1,
    activities: ['stroll'],
  },
};

export function buildingDef(type: string): BuildingDef {
  const def = BUILDINGS[type];
  if (!def) throw new Error(`unknown building type: ${type}`);
  return def;
}
