import type { BuildingDef } from '../sim/types.js';

const h = (hours: number, minutes = 0) => hours * 60 + minutes;

// M1 building set: enough to stage the bakery story from spec section 3 and give residents
// homes, work, gathering places and somewhere green to wander. Economy values arrive in M2.
export const BUILDINGS: Record<string, BuildingDef> = {
  tent: {
    type: 'tent',
    cost: 0,
    blurb: 'A canvas roof for one.',
    name: 'Tent',
    kind: 'home',
    size: [1, 1],
    emits: {},
    radius: 0,
    activities: ['sleep', 'eat', 'rest'],
    capacity: 1,
  },
  cottage: {
    type: 'cottage',
    cost: 10,
    blurb: 'An empty home: build one and someone new moves in.',
    name: 'Cottage',
    kind: 'home',
    size: [2, 2],
    emits: {},
    radius: 0,
    activities: ['sleep', 'eat', 'rest'],
    capacity: 2,
  },
  well: {
    type: 'well',
    cost: 4,
    blurb: 'Water, and a reason to stop and chat.',
    name: 'Well',
    kind: 'civic',
    size: [1, 1],
    emits: { bustle: 0.2, water: 0.3 },
    radius: 1,
    activities: [],
  },
  commons: {
    type: 'commons',
    cost: 6,
    blurb: 'An open green for gathering and festivals.',
    comfortable: 5,
    name: 'Commons',
    kind: 'social',
    size: [3, 3],
    emits: { green: 0.4, bustle: 0.3 },
    radius: 2,
    activities: ['socialize', 'stroll'],
  },
  teahouse: {
    type: 'teahouse',
    cost: 12,
    blurb: 'Tea, warmth and evening company.',
    comfortable: 3,
    name: 'Teahouse',
    kind: 'social',
    size: [2, 2],
    emits: { bustle: 0.5, scent: 0.3 },
    radius: 2,
    activities: ['socialize', 'eat'],
    open: [h(7), h(21, 30)],
  },
  oak: {
    type: 'oak',
    cost: 0,
    blurb: 'An old tree to sit beneath.',
    comfortable: 3,
    name: 'Old oak',
    kind: 'nature',
    size: [1, 1],
    emits: { green: 0.6 },
    radius: 2,
    activities: ['socialize', 'stroll'],
  },
  brook: {
    type: 'brook',
    cost: 0,
    blurb: 'Running water.',
    name: 'Brook',
    kind: 'nature',
    size: [1, 10],
    emits: { water: 0.8, green: 0.3 },
    radius: 2,
    activities: ['stroll'],
  },
  garden: {
    type: 'garden',
    cost: 3,
    blurb: 'Plots that feed the town.',
    produces: { food: 0.9 },
    name: 'Garden plots',
    singular: 'garden plot',
    kind: 'work',
    size: [2, 2],
    emits: { green: 0.5 },
    radius: 1,
    activities: ['work', 'stroll'],
    capacity: 3,
    shift: [h(9), h(13)],
  },
  bakery: {
    type: 'bakery',
    cost: 10,
    blurb: 'Bread for everyone. The ovens start at four.',
    produces: { food: 1.2 },
    name: 'Bakery',
    kind: 'work',
    size: [2, 2],
    emits: { scent: 0.7, bustle: 0.2 },
    emitsWhenWorked: { noise: 0.8 },
    radius: 4,
    activities: ['work', 'eat'],
    capacity: 1,
    shift: [h(4), h(11)],
  },
  workshop: {
    type: 'workshop',
    cost: 8,
    blurb: 'A place to make and mend. Noisy by day.',
    name: 'Workshop',
    kind: 'work',
    size: [2, 1],
    emits: {},
    emitsWhenWorked: { noise: 0.5 },
    radius: 2,
    activities: ['work'],
    capacity: 2,
    shift: [h(9), h(17)],
  },
  woodlot: {
    type: 'woodlot',
    cost: 6,
    blurb: 'Trees tended for timber.',
    produces: { timber: 0.3 },
    name: 'Woodlot',
    kind: 'work',
    size: [2, 2],
    emits: { green: 0.6 },
    emitsWhenWorked: { noise: 0.4 },
    radius: 2,
    activities: ['work', 'stroll'],
    capacity: 2,
    shift: [h(8), h(15)],
  },
  jetty: {
    type: 'jetty',
    cost: 3,
    blurb: 'Fishing from the brook.',
    produces: { food: 0.6 },
    name: 'Fishing jetty',
    kind: 'work',
    size: [1, 1],
    emits: { water: 0.4 },
    radius: 1,
    activities: ['work', 'stroll'],
    capacity: 1,
    shift: [h(6), h(12)],
  },
  bench: {
    type: 'bench',
    cost: 2,
    blurb: 'Somewhere to sit and watch the world.',
    comfortable: 2,
    name: 'Bench',
    kind: 'decor',
    size: [1, 1],
    emits: {},
    radius: 0,
    activities: ['socialize', 'stroll'],
  },
  hedge: {
    type: 'hedge',
    cost: 1,
    blurb: 'Softens noise and adds green.',
    name: 'Hedge',
    kind: 'decor',
    size: [1, 1],
    emits: { noise: -0.6, green: 0.3 },
    radius: 2,
    activities: [],
  },
  flowerbed: {
    type: 'flowerbed',
    cost: 1,
    blurb: 'Colour and scent.',
    name: 'Flower bed',
    kind: 'decor',
    size: [1, 1],
    emits: { green: 0.3, scent: 0.3 },
    radius: 1,
    activities: ['stroll'],
  },
};

// Buildings residents dream of (M3a aspirations). They appear in the build menu once asked for.
Object.assign(BUILDINGS, {
  // Wild land around the settled valley (M3c): an 8x8 plot of woods, cleared by residents' work.
  wild: {
    type: 'wild',
    name: 'Wild land',
    kind: 'nature',
    size: [8, 8],
    emits: {},
    radius: 0,
    activities: ['work'],
    blurb: 'Woods and brambles. Cleared by hand, it opens room to build.',
  },
  orchard: {
    type: 'orchard',
    name: 'Orchard',
    kind: 'nature',
    size: [2, 2],
    emits: { green: 0.7, scent: 0.2 },
    radius: 2,
    activities: ['stroll'],
    cost: 6,
    blurb: 'Young fruit trees. Apples come at harvest.',
    passive: { food: 0.15 },
  },
  glasshouse: {
    type: 'glasshouse',
    name: 'Glasshouse',
    kind: 'work',
    size: [2, 2],
    emits: { green: 0.4 },
    radius: 1,
    activities: ['stroll'],
    cost: 14,
    blurb: 'Grows food even in winter.',
    passive: { food: 0.35 },
  },
  granary: {
    type: 'granary',
    name: 'Granary',
    kind: 'work',
    size: [2, 2],
    emits: { scent: 0.1 },
    radius: 1,
    activities: [],
    cost: 12,
    blurb: 'Puts food by for winter. What the larder can\'t hold goes here.',
  },
  // Tier buildings (M4): each opens up as the town moves up a tier.
  beehives: {
    type: 'beehives',
    name: 'Beehives',
    tier: 1,
    kind: 'work',
    size: [1, 1],
    emits: { green: 0.2, scent: 0.3 },
    radius: 1,
    activities: ['stroll'],
    cost: 4,
    blurb: 'Honey from spring to autumn, and the flowers do better for it. Opens at Hamlet.',
    passive: { food: 0.1 },
  },
  coop: {
    type: 'coop',
    name: 'Chicken coop',
    tier: 2,
    kind: 'work',
    size: [2, 1],
    emits: { bustle: 0.2, noise: 0.15 },
    radius: 1,
    activities: ['work', 'stroll'],
    capacity: 1,
    shift: [h(7), h(12)],
    cost: 8,
    blurb: 'Eggs every morning, all year round. Opens at Village.',
    produces: { food: 1.2 },
  },
  fountain: {
    type: 'fountain',
    name: 'Fountain',
    tier: 3,
    kind: 'social',
    size: [2, 2],
    emits: { water: 0.6, bustle: 0.2, green: 0.1 },
    radius: 2,
    activities: ['socialize', 'stroll'],
    comfortable: 6,
    cost: 15,
    blurb: 'The heart of a proper town. Somewhere to meet that is not the teahouse. Opens at Townlet.',
  },
  banner: {
    type: 'banner',
    name: 'Town banner',
    kind: 'decor',
    size: [1, 1],
    emits: { green: 0 },
    radius: 0,
    activities: ['stroll'],
    cost: 2,
    blurb: "A banner for the town, if someone will paint it.",
  },
} satisfies Record<string, BuildingDef>);

export function buildingDef(type: string): BuildingDef {
  const def = BUILDINGS[type];
  if (!def) throw new Error(`unknown building type: ${type}`);
  return def;
}

/** One of a building, lower case: "garden plot", not "garden plots" (review: "a garden plots"). */
export function singularName(type: string): string {
  const def = buildingDef(type);
  return def.singular ?? def.name.toLowerCase();
}
